### ISSUE TITLE
Websocket need to be replaced?

### ISSUE THREAD

**Issue by GhostLee** [thrasher-/gocryptotrader#102]
```PS D:\Projects\Go\Learning> go get github.com/thrasher-/gocryptotrader```
```package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Get https://golang.org/x/net/websocket?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)```

**Comment by GhostLee** [comment]
I have solved it.
http://blog.csdn.net/alexwoo0501/article/details/73409917

**Comment by thrasher-** [comment]
Glad to hear you resolved it! Closing issue.
