### ISSUE TITLE
Data races in the exchanges Setup and Run functions

### ISSUE THREAD

**Issue by cavapoo2** [thrasher-/gocryptotrader#105]
for example in here `(g *GDAX) Setup(exch config.ExchangeConfig)`
the Verbose and Websocket flags being written to
and here
`func (g *GDAX) Run()` , this time Verbose and Websocket flags being read, since both are separate go routines.
  
Issue is mainly caused by calling the ReloadExchange function. Do we need to reload, are these flags meant to be modified?. Is loading and unloading not sufficient?.

**Comment by thrasher-** [comment]
Loading and reloading of exchanges now uses a sync waitgroup, so this has been corrected.
