### ISSUE TITLE
Trouble with <nil> in response to Exchangeinfo() in Binance Api

### ISSUE THREAD

**Issue by Antohny-frost** [thrasher-/gocryptotrader#113]
`func main() {
	// Binance client
	binance := binance.New(API_KEY, API_SECRET)

	// Get Exchange info
	test, err := binance.GetExchangeInfo()
	fmt.Println(err, test)
}`

Response:
<nil> [ ]

Some troubles with decoding? I don't need nil
How to solve it?

**Comment by shazbert** [comment]
`package main

import (
	"fmt"

	"github.com/thrasher-/gocryptotrader/exchanges/binance"
)

func main() {
	exch := binance.Binance{}
	exch.SetDefaults()

	fmt.Println(exch.GetExchangeInfo())
}`

Make sure you use SetDefaults() because it sets up the request handler.

**Comment by Antohny-frost** [comment]
Ok.thanks. 

One more question:
When I compile for Windows. Like discribed here:

> go get github.com/thrasher-/gocryptotrader
> cd %GOPATH%\src\github.com\thrasher-\gocryptotrader
> go install
> copy %GOPATH%\src\github.com\thrasher-\gocryptotrader\config_example.json %GOPATH%\bin\config.json

I run the gocryptotrader binary than encrypt standart config.json (without changes)
It asks me a password I'm entering from config file ("Password")
And it asks to repeat and after entering it continuing to asking password again and again and nothing changes. And even if I change password in config it will repeating same.
What I did wrong?

**Comment by thrasher-** [comment]
Closing this issue, will follow up the password issue in https://github.com/thrasher-/gocryptotrader/issues/115
