### ISSUE TITLE
Concurrent websocket connection panic

### ISSUE THREAD

**Issue by gloriousCode** [thrasher-/gocryptotrader#119]
`2018/04/23 17:03:37 New websocket client connected. Connected clients: 1. Limit 1.
2018/04/23 17:03:37 GET /ws     ws      2.5198ms
2018/04/23 17:03:37 Websocket req: auth
2018/04/23 17:03:37 Websocket client authenticated successfully`
...
`panic: concurrent write to websocket connection

goroutine 139 [running]:
github.com/gorilla/websocket.(*Conn).flushFrame(0xc0422db680, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc04228b9b0)
        C:/Users/User/gocode/src/github.com/gorilla/websocket/conn.go:519 +0x66d
github.com/gorilla/websocket.(*messageWriter).Close(0xc042208018, 0xab0a20, 0xc042216780)
        C:/Users/User/gocode/src/github.com/gorilla/websocket/conn.go:642 +0x82
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc0422db680, 0xab0a20, 0xc042216780, 0xc042216780, 0x40bab963d70a3d71)
        C:/Users/User/gocode/src/github.com/gorilla/websocket/json.go:27 +0x119
main.BroadcastWebsocketMessage(0xb49b50, 0x4, 0xc042134730, 0x4, 0xb50f76, 0xd, 0xaf7080, 0xc042148080, 0xc04228bb60, 0x411a1c)
        C:/Users/User/gocode/src/github.com/thrasher-/gocryptotrader/websocket.go:121 +0xf4
main.relayWebsocketEvent(0xaf7080, 0xc042148080, 0xb50f76, 0xd, 0xc042134730, 0x4, 0xb49b50, 0x4)
        C:/Users/User/gocode/src/github.com/thrasher-/gocryptotrader/routines.go:169 +0xf0
main.TickerUpdaterRoutine()
        C:/Users/User/gocode/src/github.com/thrasher-/gocryptotrader/routines.go:215 +0x7d3
created by main.main
        C:/Users/User/gocode/src/github.com/thrasher-/gocryptotrader/main.go:129 +0xb12`

Happy to make any adjustments in the front end if needed.

**Comment by shazbert** [comment]
In Websocket.go ln:107 function SendWebsocketMessage()
change it to this:
```
// SendWebsocketMessage sends a websocket message to a specific client
func SendWebsocketMessage(id int, data interface{}) error {
	for i := range WebsocketClientHub {
		if WebsocketClientHub[i].ID == id {
			return WebsocketClientHub[i].Conn.WriteJSON(data)
		}
	}
	return nil
}
```
If that doesn't remedy the situation, Im going to have to put a mutex on var WebsocketClientHub []WebsocketClient on ln: 52

**Comment by shazbert** [comment]
How do you replicate that panic?

**Comment by shazbert** [comment]
also change this to this on ln 119:

```
// BroadcastWebsocketMessage broadcasts a websocket event message to all
// websocket clients
func BroadcastWebsocketMessage(evt WebsocketEvent) error {
	for i := range WebsocketClientHub {
		WebsocketClientHub[i].Conn.WriteJSON(evt)
	}
	return nil
}
```

**Comment by gloriousCode** [comment]
I wouldn't be able to say, it used to happen frequently but I can't say if there was a specific trigger. Likely fixed as a result of those changes. 

I figure I'll leave this open for a few weeks and monitor things and if it happens again I'll leave the logs and describe what was happening. If it doesn't happen again over 2 weeks I'll close the ticket

**Comment by shazbert** [comment]
Okay!

**Comment by gloriousCode** [comment]
This still occurs. Its harder to make happen, seems like it is easier to trigger when GCT-server first starts and I start making requests. 
Here is a full on dump. In this example, I start the application and just keep hitting refresh. Less likely to occur in a release, but still worth eliminating since right now,GCT-Front end cannot re-reun GCT server
https://pastebin.com/6v08AHL4

**Comment by thrasher-** [comment]
Thanks for the paste, the solution will be making read/write events protected by a mutex lock. I'll submit a fix for it shortly

**Comment by jsam** [comment]
@thrasher- this is still not fixed, do you need PR or is anybody else working on this?

**Comment by thrasher-** [comment]
@jsam I'll merge in a fix for this tomorrow

**Comment by jsam** [comment]
@thrasher- thank you

**Comment by thrasher-** [comment]
@jsam please try the latest master, should be fixed now

**Comment by thrasher-** [comment]
Haven't been able to replicate issue since commit with a lot of testing. Will re-open if there's any further reports.
