### ISSUE TITLE
SaveConfig websocket event does not save/update config

### ISSUE THREAD

**Issue by gloriousCode** [thrasher-/gocryptotrader#124]
See attached video demonstrating:
![2018-05-07_19-45-32](https://user-images.githubusercontent.com/9261323/39695844-496218f8-522f-11e8-8f35-76df02cc7acd.gif)
 
**Ruled out causes:**
- Front-end config caching
- Sending inaccurate data. The config data sent with the event is accurate data. See attached cut response:
`
{"Event":"SaveConfig","data":{"Cryptocurrencies":"BTC,LTC,ETH,XRP,NMC,NVC,PPC,XBT,DOGE,DASH","CurrencyExchangeProvider":"fixer","Exchanges":[{"Name":"ANX","Enabled":false,"......
`

**Possible causes:**
- GCT Server does not save, just reloads on save event
- GCT front-end appends extra data to the config object. 'SaveConfig' event sends extra data so GCT server may dismiss the event. No errors or logs are returned about it failing. See below for extra data attached per exchange:
`"Pairs":[{"Name":"BTCUSD","ParsedName":"BTCUSD","Enabled":false},{"Name":"BTCHKD","ParsedName":"BTCHKD","Enabled":true},{"Name":"BTCEUR","ParsedName":"BTCEUR","Enabled":true},{"Name":"BTCCAD","ParsedName":"BTCCAD","Enabled":true},{"Name":"BTCAUD","ParsedName":"BTCAUD","Enabled":true},{"Name":"BTCSGD","ParsedName":"BTCSGD","Enabled":true},{"Name":"BTCJPY","ParsedName":"BTCJPY","Enabled":true},{"Name":"BTCGBP","ParsedName":"BTCGBP","Enabled":true},{"Name":"BTCNZD","ParsedName":"BTCNZD","Enabled":true},{"Name":"LTCBTC","ParsedName":"LTCBTC","Enabled":true},{"Name":"DOGEBTC","ParsedName":"DOGEBTC","Enabled":true},{"Name":"STRBTC","ParsedName":"STRBTC","Enabled":true},{"Name":"XRPBTC","ParsedName":"XRPBTC","Enabled":true}]},`

**Comment by thrasher-** [comment]
By default Go will only unmarshall JSON data which it knows about (unless just put into an interface{}) so any extra fields added will be ignored with no failure or error by design. Support specifically has to be added for it. Out of curiosity, are seperators sent in the extra data for currency pairs?

**Comment by gloriousCode** [comment]
Yeah cool. Those fields are for me to easily handle things in the front-end. I strip any known seperators to be able to compare currencies.
Good to know that the extra JSON isn't considered. GCT server doesn't need to care about it.
