### ISSUE TITLE
I'd like to help

### ISSUE THREAD

**Issue by faddat** [thrasher-/gocryptotrader#14]
So, as such, I'm curious what your next steps, etc might be :).

**Comment by thrasher-** [comment]
Thanks for taking interest in the project! Our core focuses ATM are writing a website front end for the bot and complete API coverage for all exchanges. Part of the complete API coverage will be converting the exchange support into separate packages in which the bot will be a wrapper over them. Over the next few days I'll upload a docs folder which explains this in more detail.

**Comment by faddat** [comment]
I get what you mean here, that's a good technique.  Is there any reason this doesn't work with poloniex?  I thought that an odd omission since there are so many other exchanges supported.
