### ISSUE TITLE
Binance websocket 

### ISSUE THREAD

**Issue by AlessandroSpallina** [thrasher-/gocryptotrader#140]
Hey, in Readme i think there is an error, Binance supports streaming api!

**Comment by thrasher-** [comment]
Hey @AlessandroSpallina. For the table, `No` means we don't currently support websocket yet in the framework and `NA` means that the exchange doesn't support the feature. Once we add support for Binance, then we'll update it to `Yes`

**Comment by thrasher-** [comment]
Supported added in https://github.com/thrasher-/gocryptotrader/commit/42ea6ba598dde66da138f82c4f03dffb40325256
