### ISSUE TITLE
BTCC Websocket Json erro.

### ISSUE THREAD

**Issue by asalei** [thrasher-/gocryptotrader#15]
As websocket for BTCC enabled, I got the following error:

2016/11/18 20:51:09 BTCC Connected to Websocket.
2016/11/18 20:51:09 BTCC Websocket subscribing to channel: "marketdata_cnybtc".
2016/11/18 20:51:09 BTCC Websocket subscribing to channel: "grouporder_cnybtc".
2016/11/18 20:51:09 BTCC btccny: Last 774.326916 (5332.830000) High 777.974340 (5357.950000) Low 755
.040000 (5200.000000) Volume 2001814.166100
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into
 float64
2016/11/18 20:51:10 json: invalid use of ,string struct tag, trying to unmarshal unquoted value into

**Comment by thrasher-** [comment]
Thanks! Fixed in https://github.com/thrasher-/gocryptotrader/commit/553f96d69364cdde203f375caee168d7e841cabe
