### ISSUE TITLE
Huobi api changes

### ISSUE THREAD

**Issue by SavostinVladimir** [thrasher-/gocryptotrader#150]
Hi! Could you change the api for HUOBI exchange, because of new updates on Huobi api? It will need to send privateSignature soon for authorized requests! I tried to do it by myself but was fallen.
I will be grateful for your help!

**Comment by thrasher-** [comment]
Thanks, will look into this. API Ref: https://github.com/huobiapi/API_Docs_en/wiki/Signing_API_Requests

**Comment by thrasher-** [comment]
Support added in https://github.com/thrasher-/gocryptotrader/commit/4fadc6ff487d3ef61b4c08f3d7a4fb2ee3b60f25

New tool for ecdsa key generation can be found here: https://github.com/thrasher-/gocryptotrader/tree/master/tools/huobi_auth

**Comment by SavostinVladimir** [comment]
thanks!!
