### ISSUE TITLE
Gemini Sandbox authentication support / private calls

### ISSUE THREAD

**Issue by l0010o0001l** [thrasher-/gocryptotrader#152]
Heya!

I have been trying to make successful HTTP calls for a Gemini sandbox account and have been given various errors such as `WARNING -- Exchange  authenticated HTTP request called but not supported due to unset/default API keys`. The API keys are set and provided through the sandbox account.

The sandbox docs say: `Gemini's sandbox site is an instance of the Gemini Exchange that offers full exchange functionality using test funds.`

I'm able to create a session without error, just not make any private API calls. Is this intentional? Maybe I've overlooked something. Maybe this is on Gemini's end. Any help / feedback would be fantastic! Thank you.

**Comment by thrasher-** [comment]
Hey @l0010o0001l!

As you have set the API keys(API key and secret), set AuthenticatedAPISupport to true and that should resolve the issue. Let me know if you have any further issues.

**Comment by l0010o0001l** [comment]
@thrasher- You are the true beez kneez. It's like the heavens opened up and starting emitting a lovely light and this song started playing. https://www.youtube.com/watch?v=EmZvOhHF85I

Thank you!!!
