### ISSUE TITLE
okex.go: is this correct?

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#159]
I was making some changes in a version of okex.go that I just forked, and found this:

	for _, holdings := range resp.([]interface{}) {
		if reflect.TypeOf(holdings).String() == returnTypeOne {
			holdingMap := holdings.(map[string]interface{})
			holdingsNumber["amount"] = holdingMap["amount"].(float64)
			holdingsNumber["contract_name"] = holdingMap[**"amount"**].(float64)
		}
	}

Is this correct, or should it be:

holdingsNumber["contract_name"] = holdingMap[**"contract_name"**].(float64)

**Comment by shazbert** [comment]
@kempeng thanks for pointing this out!

**Comment by thrasher-** [comment]
A fix has been merged in, thanks.
