### ISSUE TITLE
Kraken.UpdateTicker: fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#167]
I am updating multiple Kraken tickers using the TickerUpdateRoutine() (routines.go), and I'm getting

fatal error: concurrent map iteration and map write.

I was wondering, whether we need to add a sync.RWMutex in the Kraken struct for the Ticker map (add locks when R/W is done to the map? 

The struct is defined in Kraken.go:

// Kraken is the overarching type across the alphapoint package
type Kraken struct {
	exchange.Base
	CryptoFee, FiatFee float64
	Ticker             map[string]Ticker
}

**Comment by thrasher-** [comment]
That would definitely be a solution as maps by default don't support concurrency and will panic if that occurs. We do this in the ticker and orderbook code as an example. If possible, could you please post the panic output when it fails?

**Comment by kempeng** [comment]
Yes, I have implemented a Mutex in my local copy of Kraken.go, but saw a large update of the kraken interface. Do you still want me to share my fix?

**Comment by thrasher-** [comment]
Yes please!

**Comment by kempeng** [comment]
Can you suggest how I best do that? Ie how to share my amended file? (still a github newbie)

**Comment by kempeng** [comment]
The changes are actually minor:
1. adding sync.Mutex to the Kraken struct in Kraken.go
2. adding
k.Lock()
defer k.Unlock()
to:  SetDefaults() in Karen.go at the top of the function

3. adding
k.Lock()
defer k.Unlock()
to: UpdateTicker() in kraken_wrapper.go just above:
	for _, x := range pairs {
		for y, z := range k.Ticker {

**Comment by shazbert** [comment]
@kempeng do you still need a hand opening a PR on this?

**Comment by thrasher-** [comment]
Fixed in https://github.com/thrasher-/gocryptotrader/commit/36b37b0571ce140b3c411e581f72568e13917fe6
