### ISSUE TITLE
error message handling in DoRequest()?

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#168]
Hi, I was pulling orderbook updates from an exchange at a high rate and was seeing that the bids/asks in my orderbook returned empty at some point. Investigating what went wrong, I noticed that the contents []byte obtained by DoRequest() (in request.go) contained this:

{"error":{"code":200,"message":"Too many requests"}}

The JSON decode of the orderbook failed on it, hence no asks/bids in the orderbook, but no error was generated.

Should this be detected and an error be generated, or is this just me "misusing" the code?

**Comment by thrasher-** [comment]
Hey! The interface sent through to DoRequest should have have support for the error JSON and handle it appropriately. DoRequest will throw an error under the following conditions;

1) http.Do request fails
2) Response from Do returns a nil result
3) Failure to read the response body
4) Failure to JSON Unmarshal the data

So a solution would be to add a error member to the struct you're passing through to DoRequest, check to see if it's populated and handle it. Please let me know if you need any help with this.

**Comment by kempeng** [comment]
Hi @thrasher-, thanks for the suggestion to include a error member, thanks works. I am building an interface to an exchange not yet included, so will build it in there. Not sure if this would be good to build into other exchange interfaces as well?

**Comment by thrasher-** [comment]
Good to hear! Most exchanges already have exchange specific error handling but there might be some missing.
