### ISSUE TITLE
error when json unmarshaling string to type string

### ISSUE THREAD

**Issue by sathishvj** [thrasher-/gocryptotrader#18]
type PoloniexResultingTrades struct {
        .... 
	//Type    string  `json:"type,string"` // this line is wrong and has to be changed to 
        Type    string  `json:"type"` 
}

The field Type was being interpreted as string of a string which threw an error. 

Please refer if needed: https://groups.google.com/forum/?fromgroups=#!topic/golang-nuts/RbQaqxStMiY

**Comment by thrasher-** [comment]
Thanks! Fixed in https://github.com/thrasher-/gocryptotrader/commit/9f6e5e637ec382fc9405b18a2e2f8259d84f4331
