### ISSUE TITLE
Kraken timestamps: int64 or float64?

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#183]
I was wondering why the time of the timestamp returned by ServerTime is int64, but the type of the timestamps used in OrderInfo is float64 (for openTm, startTm, expireTm), would it not make more sense to have these as int64's as well?

**Comment by thrasher-** [comment]
Hey @kempeng, the ServerTime API response returns a traditional unix timestamp however the other API endpoints return float64's like this: "opentm":1540870174.2212 otherwise we'd aim to use int64's for all the other endpoints too.
