### ISSUE TITLE
Unused struct and wrong fields

### ISSUE THREAD

**Issue by sathishvj** [thrasher-/gocryptotrader#19]
The struct PoloniexAuthentictedTradeHistory is not used currently.  
The function GetAuthenticatedTradeHistory should ideally be returning an array of the above struct.  Instead it is using a wrong struct (PoloniexOrder).

Additionally, the struct PoloniexAuthentictedTradeHistory has to fixed.  The Date field member should actually be:
	Date          string  `json:"date"`

It is currently wrong as: 	Date          string  `json:"data,string"`

**Comment by thrasher-** [comment]
Thanks! Fixed in https://github.com/thrasher-/gocryptotrader/commit/9f6e5e637ec382fc9405b18a2e2f8259d84f4331
