### ISSUE TITLE
liqui.io api

### ISSUE THREAD

**Issue by sathishvj** [thrasher-/gocryptotrader#22]
Have you by any chance done any work on the liqui.io api?

**Comment by thrasher-** [comment]
No not yet, but support can be added.

**Comment by sathishvj** [comment]
cool.  if i get there before you, I'll let you know and send a pull request.

**Comment by thrasher-** [comment]
FYI: https://github.com/thrasher-/gocryptotrader/commit/b167d30936ab5a1ffedd38aba4327cd3b2fada17

**Comment by sathishvj** [comment]
awesome.
