### ISSUE TITLE
Instructions on compiling for Windows

### ISSUE THREAD

**Issue by bramvbilsen** [thrasher-/gocryptotrader#229]
# New Issue

## Context

I am new (extremely new) to go and wanted to play around with this repo. I tried to compile the codebase on my Windows machine by running:
```
go build -x
```
but no binary file seems to be created. 

* Operating System: Windows 10

* GoCryptoTrader version (`gocryptotrader -version`): v0.1 pre-release.

## Expected Behavior

A runnable binary file.

## Current Behavior

No binary file at all.

## Failure Information (for bugs)

I am getting the following output from running the `build` command:
```
WORK=C:\Users\TGP\AppData\Local\Temp\go-build066393954
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install go
2. clone repo
3. build codebase

**Comment by shazbert** [comment]
With respect to the output of the build:
``` WORK=C:\Users\TGP\AppData\Local\Temp\go-build066393954 ```
Is that the only output you have received?
What go version are you running?
Can you also run a git status on your folder and cp output here?

**Comment by shazbert** [comment]
Also what happens with go install -x ?

**Comment by bramvbilsen** [comment]
@shazbert That Yes, that is the only output for the build.
I now tried running `go install -x` which does a binary file that I can execute. All runs fine now!

**Comment by shazbert** [comment]
@bramvbilsen Where did that make the executable? There seems to be a problem with go or there may be a path/ evironment var issue.

**Comment by shazbert** [comment]
@bramvbilsen close due to fix, if you need any more help join our slack and get in contact with me.

**Comment by bramvbilsen** [comment]
@shazbert Inside of my `GOPATH`: `C:\Users\TGP\go\bin`.
