### ISSUE TITLE
Kraken withdraw code

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#235]
Some code to interface with additional Kraken Withdraw APIs

package kraken

import (
	"fmt"
	"net/url"
)

const (
	krakenWithdrawStatus = "WithdrawStatus"
	krakenWithdrawCancel = "WithdrawCancel"
)

// WithdrawResponse response type
type WithdrawResponse struct {
	Refid string `json:"refid"`
}

// WithdrawStatusResponse response type
type WithdrawStatusResponse struct {
	Method string  `json:"method"`
	Aclass string  `json:"aclass"`
	Asset  string  `json:"asset"`
	Refid  string  `json:"refid"`
	TxID   string  `json:"txid"`
	Info   string  `json:"info"`
	Amount float64 `json:"amount,string"`
	Fee    float64 `json:"fee,string"`
	Time   float64 `json:"time"`
	Status string  `json:"status"`
}

// WithdrawCancelResponse response type
type WithdrawCancelResponse struct {
	Aclass string `json:"aclass"`
	Asset  string `json:"asset"`
	Refid  string `json:"refid"`
}

// WithdrawStatus gets the status of recent withdrawals
func (k *Kraken) WithdrawStatus(currency, method string) ([]WithdrawStatusResponse, error) {
	var response struct {
		Error  []string                 `json:"error"`
		Result []WithdrawStatusResponse `json:"result"`
	}

	params := url.Values{}
	params.Set("asset ", currency)
	if len(method) != 0 {
		params.Set("method", method)
	}

	if err := k.SendAuthenticatedHTTPRequest(krakenWithdrawStatus, params, &response); err != nil {
		return response.Result, err
	}

	return response.Result, GetError(response.Error)
}

// WithdrawCancel sends a withdrawal cancelation request
func (k *Kraken) WithdrawCancel(currency string, amount float64) (WithdrawCancelResponse, error) {
	var response struct {
		Error  []string               `json:"error"`
		Result WithdrawCancelResponse `json:"result"`
	}
	params := url.Values{}
	params.Set("asset ", currency)
	params.Set("key  ", "")
	params.Set("amount ", fmt.Sprintf("%f", amount))

	if err := k.SendAuthenticatedHTTPRequest(krakenWithdrawCancel, params, &response); err != nil {
		return response.Result, err
	}

	return response.Result, GetError(response.Error)
}

**Comment by shazbert** [comment]
@kempeng Thanks for the code!

**Comment by kempeng** [comment]
Great! Thanks for "absorbing" the code

**Comment by thrasher-** [comment]
Thanks @kempeng!
