### ISSUE TITLE
Hardcoded ticker name index in poloniex.go

### ISSUE THREAD

**Issue by sathishvj** [thrasher-/gocryptotrader#24]
In poloniex.go, the below lines with hardcoded indexes are not correct.  
```
tickerPrice.FirstCurrency = currency[0:3]
tickerPrice.SecondCurrency = currency[3:]
```

The ticker result is sometimes as shown below where there are there more than 4 chars in the ticker code:
```
USDT_DASH: {
    .....
},
```

**Comment by thrasher-** [comment]
Thanks! Issue has been fixed in https://github.com/thrasher-/gocryptotrader/commit/5bdcf9e2ea197bc1088240831174f80b9e01659a
