### ISSUE TITLE
pair.CurrencyPair functions vs methods

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#241]
#I was wondering whether there is a principle design reason why the GCT lib has main functions with pair.CurrencyPair as first (or only) input param, instead of defining these functions as a method to pair.CurrencyPair? (to a lesse extend, same holds true for pair.CurrencyItem)

I would prefer these functions to be methods, as it make code less verbose.

Happy to work on it

**Comment by shazbert** [comment]
@kempeng Can you please provide a code example of how you want it done, or example? I do not understand.

**Comment by kempeng** [comment]
Sure, I was referring to several of the functions in currency/currency.go, like
func IsCryptoPair(p pair.CurrencyPair) bool {}
and change it into
func (p CurrencyPair) IsCryptoPair() bool {}

so you can call pair.IsCryptoPair() instead of currency.IsCryptoPair(pair)

I realised later than doing this is a bit more complicated than simply moving these functions to currency/pair/pair.go due to the dependency of these functions on variables defined in currency.go, but I think it can be solved.

Also, perhaps it worth considering changing functions like 

// IsCryptocurrency checks if the currency passed is an enabled CRYPTO currency.
func IsCryptocurrency(currency string) bool {}

to a method function of pair.CurrencyItem:
func (c CurrencyItem) IsEnabledCrypto() bool {}
to give these functions a bit stronger typing ....

**Comment by shazbert** [comment]
@kempeng  Perfect I will introduce into a PR I am currency working on, thanks for clarifying

**Comment by kempeng** [comment]
Perhaps we can change pairs.go into something like this (this will break GCT for now)

`package pair

import (
	"math/rand"
	"strings"

	"github.com/thrasher-/gocryptotrader/common"
	"github.com/thrasher-/gocryptotrader/currency"
)

const (
	// DefaultBaseCurrency is the base currency used for conversion
	DefaultBaseCurrency = "USD"
	// DefaultCurrencies has the default minimum of FIAT values
	DefaultCurrencies = "USD,AUD,EUR,CNY"
	// DefaultCryptoCurrencies has the default minimum of crytpocurrency values
	DefaultCryptoCurrencies = "BTC,LTC,ETH,DOGE,DASH,XRP,XMR"
)

// CurrencyItem is an exported string with methods to manipulate the data instead
// of using array/slice access modifiers
type CurrencyItem string

// Lower converts the CurrencyItem object c to lowercase
func (c CurrencyItem) Lower() CurrencyItem {
	return CurrencyItem(strings.ToLower(string(c)))
}

// Upper converts the CurrencyItem object c to uppercase
func (c CurrencyItem) Upper() CurrencyItem {
	return CurrencyItem(strings.ToUpper(string(c)))
}

// String converts the CurrencyItem object c to string
func (c CurrencyItem) String() string {
	return string(c)
}

// CurrencyPair holds currency pair information
type CurrencyPair struct {
	Delimiter      string       `json:"delimiter"`
	FirstCurrency  CurrencyItem `json:"first_currency"`
	SecondCurrency CurrencyItem `json:"second_currency"`
}

// CurrencyPairs define a slice of currency pairs
type CurrencyPairs []CurrencyPair

// Pair returns a currency pair string
func (c CurrencyPair) Pair() CurrencyItem {
	return c.FirstCurrency + CurrencyItem(c.Delimiter) + c.SecondCurrency
}

// Display formats and returns the currency based on user preferences,
// overriding the default Pair() display
func (c CurrencyPair) Display(delimiter string, uppercase bool) CurrencyItem {
	var pair CurrencyItem

	if delimiter != "" {
		pair = c.FirstCurrency + CurrencyItem(delimiter) + c.SecondCurrency
	} else {
		pair = c.FirstCurrency + c.SecondCurrency
	}

	if uppercase {
		return pair.Upper()
	}
	return pair.Lower()
}

// Equal compares two currency pairs and returns whether or not they are equal
func (c CurrencyPair) Equal(p CurrencyPair, exact bool) bool {
	if !exact {
		if c.FirstCurrency.Upper() == p.FirstCurrency.Upper() &&
			c.SecondCurrency.Upper() == p.SecondCurrency.Upper() ||
			c.FirstCurrency.Upper() == p.SecondCurrency.Upper() &&
				c.SecondCurrency.Upper() == p.FirstCurrency.Upper() {
			return true
		}
	} else {
		if c.FirstCurrency.Upper() == p.FirstCurrency.Upper() &&
			c.SecondCurrency.Upper() == p.SecondCurrency.Upper() {
			return true
		}
	}
	return false
}

// Swap swaps the pairs first and second currencies
func (c CurrencyPair) Swap() CurrencyPair {
	p := c
	p.FirstCurrency = c.SecondCurrency
	p.SecondCurrency = c.FirstCurrency
	return p
}

// Empty returns whether or not the pair is empty
func (c CurrencyPair) Empty() bool {
	if c.FirstCurrency == "" || c.SecondCurrency == "" {
		return true
	}
	return false
}

// NewCurrencyPairDelimiter splits the desired currency string at delimeter,
// the returns a CurrencyPair struct
func NewCurrencyPairDelimiter(currency, delimiter string) CurrencyPair {
	result := strings.Split(currency, delimiter)
	return CurrencyPair{
		Delimiter:      delimiter,
		FirstCurrency:  CurrencyItem(result[0]),
		SecondCurrency: CurrencyItem(result[1]),
	}
}

// NewCurrencyPair returns a CurrencyPair without a delimiter
func NewCurrencyPair(firstCurrency, secondCurrency CurrencyItem) CurrencyPair {
	return CurrencyPair{
		FirstCurrency:  CurrencyItem(firstCurrency),
		SecondCurrency: CurrencyItem(secondCurrency),
	}
}

// NewCurrencyPairFromIndex returns a CurrencyPair via a currency string and
// specific index
func NewCurrencyPairFromIndex(currency, index string) CurrencyPair {
	i := strings.Index(currency, index)
	if i == 0 {
		return NewCurrencyPair(CurrencyItem(currency[0:len(index)]), CurrencyItem(currency[len(index):]))
	}
	return NewCurrencyPair(CurrencyItem(currency[0:i]), CurrencyItem(currency[i:]))
}

// NewCurrencyPairFromString converts currency string into a new CurrencyPair
// with or without delimeter
func NewCurrencyPairFromString(currency string) CurrencyPair {
	delimiters := []string{"_", "-"}
	var delimiter string
	for _, x := range delimiters {
		if strings.Contains(currency, x) {
			delimiter = x
			return NewCurrencyPairDelimiter(currency, delimiter)
		}
	}
	return NewCurrencyPair(CurrencyItem(currency[0:3]), CurrencyItem(currency[3:]))
}

// Contains checks to see if a specified pair exists inside a currency pair
// array
func (pairs CurrencyPairs) Contains(p CurrencyPair, exact bool) bool {
	for x := range pairs {
		if pairs[x].Equal(p, exact) {
			return true
		}
	}
	return false
}

// ContainsCurrency checks to see if a pair contains a specific currency
func (p CurrencyPair) ContainsCurrency(c CurrencyItem) bool {
	return p.FirstCurrency.Upper() == c.Upper() ||
		p.SecondCurrency.Upper() == c.Upper()
}

// RemovePairsByFilter checks to see if a pair contains a specific currency
// and removes it from the list of pairs
func RemovePairsByFilter(p []CurrencyPair, filter CurrencyItem) []CurrencyPair {
	var pairs []CurrencyPair
	for x := range p {
		if p[x].ContainsCurrency(filter) {
			continue
		}
		pairs = append(pairs, p[x])
	}
	return pairs
}

// FormatPairs formats a string array to a list of currency pairs with the
// supplied currency pair format
func FormatPairs(pairs []string, delimiter, index string) []CurrencyPair {
	var result []CurrencyPair
	for x := range pairs {
		if pairs[x] == "" {
			continue
		}
		var p CurrencyPair
		if delimiter != "" {
			p = NewCurrencyPairDelimiter(pairs[x], delimiter)
		} else {
			if index != "" {
				p = NewCurrencyPairFromIndex(pairs[x], index)
			} else {
				p = NewCurrencyPair(CurrencyItem(pairs[x][0:3]), CurrencyItem(pairs[x][3:]))
			}
		}
		result = append(result, p)
	}
	return result
}

// CopyPairFormat copies the pair format from a list of pairs once matched
func (p CurrencyPair) CopyPairFormat(pairs CurrencyPairs, exact bool) CurrencyPair {
	for x := range pairs {
		if p.Equal(pairs[x], exact) {
			return pairs[x]
		}
	}
	return CurrencyPair{}
}

// FindPairDifferences returns pairs which are new or have been removed
func FindPairDifferences(oldPairs, newPairs []string) ([]string, []string) {
	var newPs, removedPs []string
	for x := range newPairs {
		if newPairs[x] == "" {
			continue
		}
		if !common.StringDataCompareUpper(oldPairs, newPairs[x]) {
			newPs = append(newPs, newPairs[x])
		}
	}
	for x := range oldPairs {
		if oldPairs[x] == "" {
			continue
		}
		if !common.StringDataCompareUpper(newPairs, oldPairs[x]) {
			removedPs = append(removedPs, oldPairs[x])
		}
	}
	return newPs, removedPs
}

// PairsToStringArray returns a list of pairs as a string array
func (pairs CurrencyPairs) StringSlice() []string {
	var p []string
	for x := range pairs {
		p = append(p, pairs[x].Pair().String())
	}
	return p
}

// RandomPairFromPairs returns a random pair from a list of pairs
func (pairs CurrencyPairs) RandomPair() CurrencyPair {
	pairsLen := len(pairs)

	if pairsLen == 0 {
		return CurrencyPair{}
	}

	return pairs[rand.Intn(pairsLen)]
}

// IsDefaultCurrency checks if the currency passed in matches the default fiat
// currency
func (c CurrencyItem) IsDefaultCurrency() bool {
	defaultCurrencies := common.SplitStrings(currency.DefaultCurrencies, ",")
	return common.StringDataCompare(defaultCurrencies, c.Upper().String())
}

// IsDefaultCryptocurrency checks if the currency passed in matches the default
// cryptocurrency
func (c CurrencyItem) IsDefaultCryptocurrency() bool {
	cryptoCurrencies := common.SplitStrings(currency.DefaultCryptoCurrencies, ",")
	return common.StringDataCompare(cryptoCurrencies, c.Upper().String())
}

// IsFiatCurrency checks if the currency passed is an enabled fiat currency
func (c CurrencyItem) IsFiatCurrency() bool {
	return common.StringDataCompare(currency.FiatCurrencies, c.Upper().String())
}

// IsCryptocurrency checks if the currency passed is an enabled CRYPTO currency.
func (c CurrencyItem) IsCryptocurrency() bool {
	return common.StringDataCompare(currency.CryptoCurrencies, c.Upper().String())
}

// IsCryptoPair checks to see if the pair is a crypto pair e.g. BTCLTC
func (p CurrencyPair) IsCryptoPair() bool {
	return p.FirstCurrency.IsCryptocurrency() &&
		p.SecondCurrency.IsCryptocurrency()
}

// IsCryptoFiatPair checks to see if the pair is a crypto fiat pair e.g. BTCUSD
func (p CurrencyPair) IsCryptoFiatPair() bool {
	return p.FirstCurrency.IsCryptocurrency() && !p.SecondCurrency.IsCryptocurrency() ||
		!p.FirstCurrency.IsCryptocurrency() && p.SecondCurrency.IsCryptocurrency()
}

// IsFiatPair checks to see if the pair is a fiat pair e.g. EURUSD
func (p CurrencyPair) IsFiatPair() bool {
	return p.FirstCurrency.IsFiatCurrency() &&
		p.SecondCurrency.IsFiatCurrency()
}`

**Comment by shazbert** [comment]
```go puts the formatting in the text. I will check this out soon thanks.

**Comment by shazbert** [comment]
Closing due to #247
