### ISSUE TITLE
Are forex rates updated()

### ISSUE THREAD

**Issue by kempeng** [thrasher-/gocryptotrader#242]
I have been searching the GCT library, and examining the currency & forexproviders libraries to understand how forex rate are regularly updated, but in gst/main.go I can only find that the forex rates are setup and seeded with:

```
currency.FXProviders = forexprovider.StartFXService(bot.config.GetCurrencyConfig().ForexProviders)
	log.Debugf("Primary forex conversion provider: %s.\n", bot.config.GetPrimaryForexProvider())
	err = bot.config.RetrieveConfigCurrencyPairs(true)
	if err != nil {
		log.Fatalf("Failed to retrieve config currency pairs. Error: %s", err)
	}
	log.Debugf("Successfully retrieved config currencies.")
	log.Debugf("Fetching currency data from forex provider..")
	err = currency.SeedCurrencyData(common.JoinStrings(currency.FiatCurrencies, ","))
	if err != nil {
		log.Fatalf("Unable to fetch forex data. Error: %s", err)
	}

```
But they dont seem to get updated regulalry (ie hourly/daily)? Am I overlooking something?

**Comment by thrasher-** [comment]
That's correct, they are seeded once per session of GCT as we don't yet have rate limiters configured for the different forex providers. As part of this implementation, I think having the option to refresh per the rate limit will be good, but also have the ability for the user to cache it to disk and refresh it upon expiration duration (e.g every X hrs) if the user isn't interested in as close to real time forex rates as possible.

Will aim to at least have coverage for the currencyconvterapi default provider done shortly.

**Comment by kempeng** [comment]
My application does dependent on up to date forex rates. As I work around, I just call SeedCurrencyData() to get the FXRate updated, but it would be nice if we had something like: UpdateCurrencyData()

BTW, I also created an implementation for 1Forge, they offer a free 1000x/day plan to pull current foex rates for all major FIATs ... Can share if you like

// UpdateCurrencyData returns rates correlated with suported currencies
func UpdateCurrencyData(currencies string) error {
	
	newRates, err := FXProviders.GetCurrencyData(BaseCurrency, currencies)
	if err != nil {
		return err
	}

	for key, value := range newRates {
		FXRates[key] = value
	}

	return nil
}

**Comment by thrasher-** [comment]
Forex rates are now updated as per PR: https://github.com/thrasher-/gocryptotrader/commit/0990f9d118b2fd044bbadefe71b29fd730ca932f
