### ISSUE TITLE
CoinbasePro websocket crashes

### ISSUE THREAD

**Issue by jeee** [thrasher-/gocryptotrader#268]
Turning on the CoinbasePro websocket crashes the program (using default config.json):

[INFO]:  2019/04/03 22:39:12 CoinbasePro BTC-GBP SPOT: TICKER: Last $5265.32 USD (£3998.98 GBP) Ask $0.00 USD (£0.00 GBP) Bid $0.00 USD (£0.00 GBP) High $5338.61 USD (£4054.65 GBP) Low $4793.34 USD (£3640.52 GBP) Volume 1928.81197730
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x875be7]

goroutine 621 [running]:
github.com/thrasher-/gocryptotrader/exchanges/coinbasepro.(*CoinbasePro).ProcessSnapshot(0xc0000bfd40, 0xc000660690, 0x3fe00, 0xa9fb60)
        /home/jeee/gocryptotrader/exchanges/coinbasepro/coinbasepro_websocket.go:214 +0x157
github.com/thrasher-/gocryptotrader/exchanges/coinbasepro.(*CoinbasePro).WsHandleData(0xc0000bfd40)
        /home/jeee/gocryptotrader/exchanges/coinbasepro/coinbasepro_websocket.go:176 +0x69b
created by github.com/thrasher-/gocryptotrader/exchanges/coinbasepro.(*CoinbasePro).WsConnect
        /home/jeee/gocryptotrader/exchanges/coinbasepro/coinbasepro_websocket.go:87 +0x313

**Comment by xtda** [comment]
Thanks for the report

I have opened up https://github.com/thrasher-/gocryptotrader/pull/269 that will fix this issue
