### ISSUE TITLE
Error bitmex ticker

### ISSUE THREAD

**Issue by thorjeus** [thrasher-/gocryptotrader#282]
Hi Dev,

I got this when running for a while

[ERROR]: 2019/04/22 17:23:18 Failed to get XBTUSD Bitmex ticker. Error: Bitmex REST error: no ticker return

Could you please advise what to change/fix?
Appreciate for your help.

Thanks.

**Comment by thrasher-** [comment]
Commit https://github.com/thrasher-/gocryptotrader/commit/32e4dcb63dae351c8f97b6289ef564d2ff14f4f7 fixes this however the ticker functionality is quite limited as Bitmex doesn't offer a ticker endpoint https://www.bitmex.com/api/explorer/. The two options are a) Query last trade data to find the price and amount (which is what we use) b) Query the orderbook data to obtain the best bid/ask
