### ISSUE TITLE
[Bittrex] PlaceBuyLimit / PlaceSellLimit does not work

### ISSUE THREAD

**Issue by chaeso** [thrasher-/gocryptotrader#44]
The bug can be fixed if you change as follows.

e.g., bittrexAPIGetBalances => bittrexAPIBuyLimit

`func (b *Bittrex) PlaceBuyLimit(currencyPair string, quantity, rate float64) ([]UUID, error) {
        ....
	path := fmt.Sprintf("%s/%s", bittrexAPIURL, bittrexAPIGetBalances) . `

**Comment by thrasher-** [comment]
Thanks! Should be fixed now: https://github.com/thrasher-/gocryptotrader/commit/9bdc316ae8ff03bec2a9e7eacaba8797f6d61e76
