### ISSUE TITLE
Initial empty state of WebUI

### ISSUE THREAD

**Issue by dandaka** [thrasher-/gocryptotrader#45]
I have compiled and run GoCryptotrader. Have launched web UI. Now it looks like this:

![gocrypto](https://user-images.githubusercontent.com/2384694/29779258-ab68c8a2-8c1a-11e7-9600-b1eb4bbc87ee.png)

I have used default config file.

All links in navbar (Dashboard, Wallets, Settings) do look the same — empty. Is it normal? Or maybe I do something wrong?

**Comment by bahelit** [comment]
This is also what I'm seeing.

**Comment by backnight** [comment]
Hello guys,

Just tried the web interface too... and it's quite in a pre-alpha/not working state as far as I tested it (the web/ forder hasn't been updated for 5 months now ;) ).

I tried to make it work via docker-compose:
- Update the `Dockerfile` and add `EXPOSE 9050` line at the end (it will expose the GoCryptoTrader webserver outside of the container).
- In your config_example.dat, enable the webserver
- Update the docker-compose.yml file and add the the CLI service: `ports:
            - "9050:9050"`
- Run `docker-compose build` to build the new images
- Run `docker-compose up` to launch GoCryptoTrader and GoCryptoTrader web

To make it work a little bit more:
- About the web container The bower packages are not installed by default. If you look at you browser Developer Tools > Network when you go at 'http://localhost:3333', you will see that all bower_components/ paths return a 404.
- To install the bower packages into the web container:
  - `docker exec -it web /bin/bash` (launch a term into the web container)
  - `./node_modules/bower/bin/bower --allow-root install` (install bower dependencies)

Now if you go on 'http://localhost:3333', you will see a loader ;)

That's all for now, didn't have the time to dig more onto this. Will continue tomorrow.

**Comment by gloriousCode** [comment]
Hey guys, I'd recommend you follow the directions in the readme. I never really considered the docker part of the application during my front-end development. I just did a fresh install and followed the readme and got the interface working.

Unfortunately, docker is not in my skillset yet.

I'm in the process of rewriting it to be using Angular 4+ and Electron

**Comment by backnight** [comment]
I'm only using dockerized applications so I will update the Docker setup of this project when you will merge the new WebGUI you are building.

**Comment by joeblew99** [comment]
is this being worked on by anyone ?

I am building Web UI's with all golang and all grpc and a tiny bit of react.  You 
can get huge gains because its all in golang and websockets now work wth GRPC.
But i can also understand if this is too golang all the way..

Try this !!!
https://github.com/johanbrandhorst/grpcweb-example

**Comment by gloriousCode** [comment]
This isn't the place to advertise your project. The front-end is still being worked on.

**Comment by joeblew99** [comment]
@gloriousCode is you change your mind let me know.

i have built a GUI's already using the project i referenced.
