### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by backnight** [thrasher-/gocryptotrader#46]
Hello,

There is a web/ folder in the repository which hasn't been updated for 5 months now.
I would like to know if there is still someone working on it or if it has been moved to another repository, etc?

Thanks a lot for all the work!

**Comment by gloriousCode** [comment]
Hello backnight, as I mentioned in the previous issue, I'm in the process of rewriting the front-end to be using Angular 4+ and Electron. I've put the repo on my own profile and will merge back to this main one once I've replicated functionality of this one.
It's over here: https://github.com/gloriousCode/gocryptotrader/

**Comment by mattkanwisher** [comment]
I tried both the fork and the ui in this repo, neither seem to have any ability to manage your wallet. How are you using the trading system? You just using the command line tools, or manually changing the config file?

**Comment by gloriousCode** [comment]
Hello Matthew!

Thanks for your interest in this project. This project is in active development. There are plans to manage wallets from both cli and the ui. You can track progress via trello at https://trello.com/b/ZAhMhpOy/gocryptotrader or checkout the readme for the slack channel details!

On 11 Oct 2017, at 9:51 pm, Matthew Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried both the fork and the ui in this repo, neither seem to have any ability to manage your wallet. How are you using the trading system? You just using the command line tools, or manually changing the config file?

**Comment by mattkanwisher** [comment]
Do either work now? Is it possible at all to manage the wallets, or you not that far along?
