### ISSUE TITLE
API HTTP request timeout

### ISSUE THREAD

**Issue by brunocassol** [thrasher-/gocryptotrader#49]
I'd love to be able to specify a timeout for all API requests. For example I would not be happy if my buyLimit or sellLimit takes too long to execute in a highly volatile market.

Even better is to also be able to provide my own custom HTTP handler where I can set other configurations along with timeout.

Currently the API uses a default HTTP handler as can be seen here: https://github.com/thrasher-/gocryptotrader/blob/9671368f596c2b33253a374294f2ab5fb0838dc4/common/common.go#L277

@toorop achieves this in his Bittrex API by providing a NewWithCustomHttpClient() constructor: https://github.com/toorop/go-bittrex/blob/48e6248b8c9b29d3eb8ce0359a0f794fc17000e5/bittrex.go#L27

Please let me know if I wasn't clear enough.
Thanks for sharing this codebase! It's proving very useful!

**Comment by shazbert** [comment]
This definitely will be implemented, thank you for your constructive feedback.

**Comment by shazbert** [comment]
#99 Check this out and let me know what features to add if any. 
@brunocassol

**Comment by brunocassol** [comment]
Awesome! Thank you! This is what I needed.
