### ISSUE TITLE
Ripple XRP 'Tag' Field

### ISSUE THREAD

**Issue by karma0** [thrasher-/gocryptotrader#54]
Is there a way to refer to an XRP Tag within the PortfolioAddresses in the config?  There seems to be a reference to XRP in the bitstamp code that refers to a 'destTag', but that's all I'm able to find.

**Comment by karma0** [comment]
Is "EnabledPairs" a reference to the pairs that are currently supported by the software at the moment?  If I'm working with Bitfinex with XRP and BTC, for example, could I just add an XRP & BTC portfolio addresses and then "XRPBTC" to the EnabledPairs list in the config, or does there have to be support for it in the `exchange/bitfinex` code?

If it has to be built-out in the code, is the Bitstamp implementation a good source for an example to build upon?

**Comment by shazbert** [comment]
@karma0 Have you been in contact with anybody on our Slack about this issue?

**Comment by shazbert** [comment]
@karma0 Portfolio code and exchange code are currently segregated. We will be adding support for all available cryptocurrencies supported by the exchanges for portfolio tracking and monitoring including ripple. ```Enabled pairs``` are pairs that you want to use in the package the ```available pairs``` are the current supported pairs by the exchange, so adding to enabled pairs manually requires you to verify what's in available pairs or do a manual update to available pairs if ```auto pair updating``` is not supported,  a better explanation will occur when we do a documentation overhaul before version tag and binary release, but that is still a while off yet. Yes the Bitstamp is a good implementation to build upon, we are striving to update and improve all code.

I hope this helps answer any questions if they needed answering, please open this back up if you need more clarification or join our slack.
