### ISSUE TITLE
How to run this thing?

### ISSUE THREAD

**Issue by AidasK** [thrasher-/gocryptotrader#61]
I have followed your steps, but it does not run.
```sh
go get github.com/thrasher-/gocryptotrader
cd $GOPATH/src/github.com/thrasher-/gocryptotrader
go install
cp $GOPATH/src/github.com/thrasher-/gocryptotrader/config_example.dat $GOPATH/bin/config.da
./$GOPATH/bin/gocryptotrader
```
output:
```
...
...
goroutine 113 [running]:
net/url.url.Values.Set(...)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/url/url.go:790
github.com/thrasher-/gocryptotrader/exchanges/bitfinex.(*Bitfinex).UpdateOrderbook(0xc42007fd40, 0x0, 0x0, 0xc42001c300, 0x3, 0xc42001c303, 0x3, 0xc420018c50, 0x4, 0x0, ...)
	/Users/aidas/go/src/github.com/thrasher-/gocryptotrader/exchanges/bitfinex/bitfinex_wrapper.go:83 +0xb1
main.OrderbookUpdaterRoutine()
	/Users/aidas/go/src/github.com/thrasher-/gocryptotrader/routines.go:255 +0x67f
created by main.main
	/Users/aidas/go/src/github.com/thrasher-/gocryptotrader/main.go:205 +0x10b2
```

I have also tried docker `docker-compose up` but it says:
```
Building web
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by kplimack** [comment]
ive tried building the webui manually, but to no avail either.  https://github.com/thrasher-/gocryptotrader/blob/master/web/README.md

**Comment by AidasK** [comment]
1. I managed to launch it by turning off "Bitfinex" trader in the config.
2. I have launched web interface with "npm run start:web"
But web console contains some errors: 
<img width="1433" alt="screen shot 2017-11-05 at 20 20 01" src="https://user-images.githubusercontent.com/2088484/32417726-bfa90b56-c266-11e7-93fa-f3926d2553f0.png">
I tried running both on the same time, but websocket could not connect to 9050 port.  What I am missing? 
I have also enabled webserver in the config, but all it says "GoCryptoTrader RESTful interface. For the web GUI, please visit the web GUI readme." and WS does not work jet.

**Comment by kplimack** [comment]
i did the same thing, but i get a spinny wheel in the UI, are you able to get some data ?

**Comment by AidasK** [comment]
No. I think this `bot` is not a bot at this time. It is in an early stage and has no strategies installed. So it is no use for me.

**Comment by gloriousCode** [comment]
The go application must be running when running the web UI. It currently only supports the default username and password - so if you've changed that, then the websocket will not authenticate.

The dockerfile is out of date. I'll add to the trello to remove it.

**Comment by firegnome** [comment]
@kplimack You probably have to enable the Webserver in config.dat file on line 52.

**Comment by ahmetabdi** [comment]
@gloriousCode Rather than removing wouldn't it be better to fix it?

**Comment by gloriousCode** [comment]
@ahmetabdi 
I would be happy to review any pull request to fix it. I don't have experience with docker and it was originally kindly provided via pull request
