### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by RDash21** [thrasher-/gocryptotrader#7]
Hello there,

I am running into the following error:
# github.com/thrasher-/gocryptotrader
go/src/github.com/thrasher-/gocryptotrader/poloniexwebsocket.go:135: not enough arguments in call to turnpike.NewWebsocketClient

Personally I know this is not production yet, personally I wanted to see how it works.

Regards,
RDash

**Comment by thrasher-** [comment]
Hi,

It seems as though the version of turnpike you have differs to the one the bot uses. You'll need the following dependencies:

```
go get github.com/gorilla/websocket
go get github.com/toorop/go-pusher
go get github.com/thrasher-/socketio
go get gopkg.in/jcelliott/turnpike.v2
```

These are the packages the bot uses for build testing, which pass successfully. So this should resolve your issue.

**Comment by RDash21** [comment]
Hello there,

Sorry for the late reply, its been a busy week.

The issue still remains:

rdash@srv1:~$ export GOPATH=$HOME/go
rdash@srv1:~$ export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
rdash@srv1:~$ go get github.com/gorilla/websocket
rdash@srv1:~$ go get github.com/toorop/go-pusher
rdash@srv1:~$ go get github.com/thrasher-/socketio
rdash@srv1:~$ go get gopkg.in/jcelliott/turnpike.v2
rdash@srv1:~$ go get github.com/thrasher-/gocryptotrader
# github.com/thrasher-/gocryptotrader
go/src/github.com/thrasher-/gocryptotrader/poloniexwebsocket.go:135: not enough arguments in call to turnpike.NewWebsocketClient
rdash@srv1:~$

**Comment by thrasher-** [comment]
Latest commit should fix this issue, let me know how you go.

**Comment by RDash21** [comment]
Hello there,

Been away for a little wile due various of things. My apologies for the very delayed response.


Currently running:
Debian Jessie (8)

Hitting on the following error: 
$ go get github.com/thrasher-/gocryptotrader
# github.com/toorop/go-pusher
go/src/github.com/toorop/go-pusher/client.go:132: undefined: client
# github.com/gorilla/websocket
go/src/github.com/gorilla/websocket/client.go:361: unknown tls.Config field 'GetCertificate' in struct literal
