### ISSUE TITLE
Lost Dockerfile in web directory 

### ISSUE THREAD

**Issue by xbee** [thrasher-/gocryptotrader#91]
There is not exists a Dockerfile in web directory, but refenerced in docker-compose.yml

**Comment by gloriousCode** [comment]
Hello,
That dockerfile was provided to us before rewriting the front-end.
I've just created a ticket in our Trello to adress this: https://trello.com/c/5RjuUs39/62-learn-docker-create-a-new-docker-file-to-build-server-and-front-end
