### ISSUE TITLE
Selective test option (test gdax only in ./testdata/configtest.json"). 

### ISSUE THREAD

**Issue by cavapoo2** [thrasher-/gocryptotrader#97]
If i want to say test gdax only, then it fails. I edited the testdata/configtest.json to only have gdax. 
I can see some hardcoded strings for Btifinex so probably issue is something to do with this, so maybe a more programmatic test that reads the config and just tests whatever the config requires is needed ?.

I can try to help with this.

**Comment by cavapoo2** [comment]
Hi i made a fix for this. Can you check it to see if its ok. https://github.com/cavapoo2/gocryptotrader/commit/0ccafe7bf6579b9a7ebe778fbb4ffbe239a4d257
https://github.com/cavapoo2/gocryptotrader/commit/50b7ae3692677b259f681983b8e1895deff912f1
https://github.com/cavapoo2/gocryptotrader/commit/98b6ee633e0868d223db6768d4f6bc9009d5f268

Let me know if this is ok.

**Comment by shazbert** [comment]
We are going to be increasing modularity across the entire codebase even the exchange packages themselves. For now I don't think these updates will not be needed. Thanks for the idea, we might implement this feature in the future.
